/**:
  ros__parameters:
    side_shift:
      min_distance_to_start_shifting: 1.5
      time_to_start_shifting: 1.0
      shifting_lateral_jerk: 0.2
      min_shifting_distance: 1.5
      min_shifting_speed: 1.0
      shift_request_time_limit: 1.0
      publish_debug_marker: true
