/**:
  ros__parameters:
    # constraints param for normal driving
    normal:
      min_acc: -2.0         # min deceleration [m/ss]
      max_acc: 4.0          # max acceleration [m/ss]
      min_jerk: -1.0        # min jerk [m/sss]
      max_jerk: 2.0         # max jerk [m/sss]

    slow_down:
      min_acc: -1.0         # min deceleration [m/ss]
      min_jerk: -1.0        # min jerk [m/sss]

    # constraints to be observed
    limit:
      min_acc: -3.0         # min deceleration limit [m/ss]
      max_acc: 2.0          # max acceleration limit [m/ss]
      min_jerk: -2.5        # min jerk limit [m/sss]
      max_jerk: 2.5         # max jerk limit [m/sss]
